// Wylie Neuro — Score Index
// Used by popup for fast search
// Auto-synced from scores.js (DIVISIONS + CALCS) — keep in sync when scores.js changes

const SCORE_INDEX = [
  // NEUROVASKULAR
  {name:"NIHSS",full:"NIH Stroke Scale",division:"Neurovaskular",tags:["severity","monitoring"],hasCalc:true},
  {name:"mRS",full:"Modified Rankin Scale",division:"Neurovaskular",tags:["prognosis","monitoring"],hasCalc:false},
  {name:"Siriraj Score",full:"Siriraj Stroke Score",division:"Neurovaskular",tags:["diagnosis"],hasCalc:true},
  {name:"Hunt & Hess",full:"Hunt and Hess Scale — SAH",division:"Neurovaskular",tags:["severity","prognosis"],hasCalc:false},
  {name:"Fisher Scale",full:"Fisher CT Grading Scale — SAH",division:"Neurovaskular",tags:["severity","prognosis"],hasCalc:true},
  {name:"Modified Fisher",full:"Modified Fisher Scale — SAH",division:"Neurovaskular",tags:["severity","prognosis"],hasCalc:true},
  {name:"ICH Score",full:"Intracerebral Hemorrhage Score",division:"Neurovaskular",tags:["prognosis","severity"],hasCalc:true},
  {name:"CHA₂DS₂-VASc",full:"Cardiac Failure/HT/Age/DM/Stroke/Vascular/Age/Sex",division:"Neurovaskular",tags:["screening","treatment"],hasCalc:true},
  {name:"HAS-BLED",full:"Hypertension/Abnormal Renal&Liver/Stroke/Bleeding/Labile INR/Elderly/Drugs",division:"Neurovaskular",tags:["screening","treatment"],hasCalc:true},
  {name:"ABCD²",full:"Age/BP/Clinical/Duration/Diabetes",division:"Neurovaskular",tags:["prognosis","screening"],hasCalc:true},
  {name:"HINTS",full:"Head Impulse / Nystagmus / Test of Skew",division:"Neurovaskular",tags:["diagnosis"],hasCalc:false},
  {name:"ASPECTS",full:"Alberta Stroke Program Early CT Score",division:"Neurovaskular",tags:["diagnosis","treatment"],hasCalc:true},
  {name:"PC-ASPECTS",full:"Posterior Circulation ASPECTS",division:"Neurovaskular",tags:["diagnosis","treatment"],hasCalc:true},
  {name:"WFNS Grade",full:"World Federation of Neurosurgical Societies SAH Grade",division:"Neurovaskular",tags:["severity","prognosis"],hasCalc:false},
  {name:"Boston Criteria",full:"Boston Criteria for CAA v2.0",division:"Neurovaskular",tags:["diagnosis"],hasCalc:false},
  {name:"Barthel Index",full:"Barthel Index of ADL",division:"Neurovaskular",tags:["monitoring","prognosis"],hasCalc:false},
  {name:"tPA Kontraindikasi",full:"IV tPA Contraindications Checklist for Ischemic Stroke",division:"Neurovaskular",tags:["treatment","diagnosis"],hasCalc:true},
  {name:"Alteplase Dose",full:"Kalkulator Dosis Alteplase (tPA) — Stroke Iskemik Akut",division:"Neurovaskular",tags:["treatment"],hasCalc:true},
  {name:"sICH Score",full:"Secondary Intracerebral Hemorrhage Score",division:"Neurovaskular",tags:["diagnosis","screening"],hasCalc:true},
  {name:"Mehran Score",full:"Mehran Score for Post-PCI Contrast-Induced Nephropathy",division:"Neurovaskular",tags:["prognosis","screening"],hasCalc:true},
  {name:"mTICI",full:"Modified Treatment in Cerebral Infarction (mTICI) Score",division:"Neurovaskular",tags:["monitoring","prognosis"],hasCalc:false},
  {name:"CAVE Score",full:"CAVE Score — Risiko Late Seizure Pasca Stroke",division:"Neurovaskular",tags:["prognosis","screening"],hasCalc:true},
  {name:"SeLECT Score",full:"SeLECT Score — Prediksi Epilepsi Post-Stroke",division:"Neurovaskular",tags:["prognosis","screening"],hasCalc:true},
  {name:"CSVT Score",full:"CSVT Clinical Scoring — Cerebral Sinus Venous Thrombosis",division:"Neurovaskular",tags:["diagnosis","screening"],hasCalc:true},
  {name:"FUNC Score",full:"FUNC Score — Fungsional 90 Hari Pasca ICH",division:"Neurovaskular",tags:["prognosis"],hasCalc:true},
  {name:"UIATS",full:"Unruptured Intracranial Aneurysm Treatment Score",division:"Neurovaskular",tags:["treatment","prognosis"],hasCalc:true},
  {name:"VASIS Score",full:"VASIS — VAsovagal Syncope International Study Classification",division:"Neurovaskular",tags:["diagnosis","treatment"],hasCalc:true},
  {name:"CVT-GS",full:"CVT Grading Scale — Barboza et al. 2018",division:"Neurovaskular",tags:["prognosis","severity"],hasCalc:true},
  {name:"mGS",full:"Modified Graeb Score (mGS) — Kuantifikasi IVH",division:"Neurovaskular",tags:["severity","prognosis","monitoring"],hasCalc:true},
  {name:"Graeb Score",full:"Original Graeb Score — Intraventricular Hemorrhage",division:"Neurovaskular",tags:["severity","diagnosis"],hasCalc:true},
  // NEUROINFEKSI
  {name:"GCS",full:"Glasgow Coma Scale",division:"Neuroinfeksi",tags:["severity","monitoring"],hasCalc:true},
  {name:"FOUR Score",full:"Full Outline of Unresponsiveness Score",division:"Neuroinfeksi",tags:["severity","monitoring"],hasCalc:true},
  {name:"Thwaites TBM",full:"Thwaites Diagnostic Index for TBM",division:"Neuroinfeksi",tags:["diagnosis"],hasCalc:true},
  {name:"BM Score",full:"Bacterial Meningitis Score (Nigrovic)",division:"Neuroinfeksi",tags:["diagnosis","screening"],hasCalc:true},
  {name:"Tetanus Grade",full:"Ablett Tetanus Severity Classification",division:"Neuroinfeksi",tags:["severity","treatment"],hasCalc:true},
  {name:"APACHE II",full:"Acute Physiology and Chronic Health Evaluation II",division:"Neuroinfeksi",tags:["prognosis","severity"],hasCalc:false},
  {name:"Lancet TBM",full:"Lancet Consensus Uniform Case Definition — TBM",division:"Neuroinfeksi",tags:["diagnosis","screening"],hasCalc:true},
  // NEUROIMUNOLOGI
  {name:"GBS Disability",full:"Hughes GBS Disability Scale",division:"Neuroimunologi",tags:["severity","monitoring"],hasCalc:true},
  {name:"EGRIS",full:"Erasmus GBS Respiratory Insufficiency Score",division:"Neuroimunologi",tags:["prognosis","treatment"],hasCalc:true},
  {name:"MRC Sum Score",full:"Medical Research Council Sum Score — GBS/CIDP",division:"Neuroimunologi",tags:["severity","monitoring"],hasCalc:true},
  {name:"EDSS",full:"Expanded Disability Status Scale — Multiple Sclerosis",division:"Neuroimunologi",tags:["severity","monitoring"],hasCalc:false},
  {name:"H&Y Scale",full:"Hoehn and Yahr Scale — Parkinson",division:"Neuroimunologi",tags:["severity","monitoring"],hasCalc:true},
  {name:"MGFA Class",full:"Myasthenia Gravis Foundation of America Classification",division:"Neuroimunologi",tags:["severity","treatment"],hasCalc:true},
  {name:"QMG Score",full:"Quantitative Myasthenia Gravis Score",division:"Neuroimunologi",tags:["severity","monitoring"],hasCalc:false},
  {name:"MG-ADL",full:"Myasthenia Gravis Activities of Daily Living",division:"Neuroimunologi",tags:["monitoring"],hasCalc:false},
  {name:"EGOS",full:"Erasmus GBS Outcome Score",division:"Neuroimunologi",tags:["prognosis","monitoring"],hasCalc:true},
  {name:"McDonald 2024",full:"Revised McDonald Criteria 2024 — Diagnosis Multiple Sclerosis",division:"Neuroimunologi",tags:["diagnosis"],hasCalc:true},
  // NEUROPAIN
  {name:"DN4",full:"Douleur Neuropathique en 4 Questions",division:"Neuropain",tags:["diagnosis","screening"],hasCalc:true},
  {name:"LANSS",full:"Leeds Assessment of Neuropathic Symptoms and Signs",division:"Neuropain",tags:["diagnosis"],hasCalc:false},
  {name:"NRS Pain",full:"Numerical Rating Scale — Pain",division:"Neuropain",tags:["monitoring","severity"],hasCalc:false},
  {name:"MIDAS",full:"Migraine Disability Assessment",division:"Neuropain",tags:["severity","treatment"],hasCalc:true},
  {name:"HIT-6",full:"Headache Impact Test-6",division:"Neuropain",tags:["monitoring","severity"],hasCalc:true},
  {name:"painDETECT",full:"painDETECT Questionnaire",division:"Neuropain",tags:["screening","diagnosis"],hasCalc:false},
  {name:"Fibromyalgia WPI/SS",full:"ACR 2016 Fibromyalgia Diagnostic Criteria — WPI + SS Score",division:"Neuropain",tags:["diagnosis","screening"],hasCalc:true},
  {name:"Opioid Converter",full:"Opioid Conversion Calculator — Oral Morphine Equivalents (OME)",division:"Neuropain",tags:["treatment"],hasCalc:true},
  {name:"Benzodiazepine Converter",full:"Benzodiazepine Conversion Calculator",division:"Neuropain",tags:["treatment"],hasCalc:true},
  {name:"Steroid Converter",full:"Steroid Conversion Calculator — Anti-inflammatory Equivalence",division:"Neuropain",tags:["treatment"],hasCalc:true},
  // NEUROBEHAVIOR
  {name:"MMSE",full:"Mini-Mental State Examination",division:"Neurobehavior",tags:["screening","diagnosis"],hasCalc:true},
  {name:"MoCA",full:"Montreal Cognitive Assessment",division:"Neurobehavior",tags:["screening","diagnosis"],hasCalc:false},
  {name:"CDR",full:"Clinical Dementia Rating Scale",division:"Neurobehavior",tags:["severity","monitoring"],hasCalc:false},
  {name:"GDS-15",full:"Geriatric Depression Scale (Short Form)",division:"Neurobehavior",tags:["screening","diagnosis"],hasCalc:true},
  {name:"FAB",full:"Frontal Assessment Battery",division:"Neurobehavior",tags:["diagnosis","screening"],hasCalc:false},
  {name:"NPI",full:"Neuropsychiatric Inventory",division:"Neurobehavior",tags:["monitoring"],hasCalc:false},
  {name:"PHQ-9",full:"Patient Health Questionnaire-9",division:"Neurobehavior",tags:["screening","severity"],hasCalc:false},
  {name:"Hachinski Score",full:"Hachinski Ischemic Score",division:"Neurobehavior",tags:["diagnosis","screening"],hasCalc:true},
  {name:"ADL",full:"Barthel Index — Activities of Daily Living",division:"Neurobehavior",tags:["monitoring","severity"],hasCalc:true},
  {name:"IADL",full:"Lawton Instrumental Activities of Daily Living",division:"Neurobehavior",tags:["monitoring","screening"],hasCalc:true},
  {name:"HAM-D",full:"Hamilton Depression Rating Scale (HAM-D 17 item)",division:"Neurobehavior",tags:["severity","monitoring"],hasCalc:true},
  {name:"DASS-21",full:"Depression Anxiety Stress Scale-21 (DASS-21)",division:"Neurobehavior",tags:["screening","severity"],hasCalc:true},
  // EPILEPSI
  {name:"STESS",full:"Status Epilepticus Severity Score",division:"Epilepsi",tags:["prognosis","severity"],hasCalc:true},
  {name:"EMSE",full:"Epidemiology-based Mortality Score in SE",division:"Epilepsi",tags:["prognosis"],hasCalc:false},
  {name:"Engel Class",full:"Engel Outcome Classification Post-Surgery",division:"Epilepsi",tags:["prognosis"],hasCalc:false},
  {name:"QOLIE-31",full:"Quality of Life in Epilepsy Inventory-31",division:"Epilepsi",tags:["monitoring"],hasCalc:false},
  {name:"Sheldon Score",full:"Sheldon Score — Diferensiasi Kejang vs Sinkop",division:"Epilepsi",tags:["diagnosis","screening"],hasCalc:true},
  {name:"Dosis AED",full:"Kalkulator Dosis Obat Anti-Epilepsi",division:"Epilepsi",tags:["treatment"],hasCalc:true},
  // NEUROMUSKULER
  {name:"MRC Scale",full:"Medical Research Council Muscle Strength Scale",division:"Neuromuskuler",tags:["severity","monitoring"],hasCalc:true},
  {name:"ALSFRS-R",full:"ALS Functional Rating Scale-Revised",division:"Neuromuskuler",tags:["monitoring","prognosis"],hasCalc:false},
  {name:"El Escorial",full:"El Escorial Revised ALS Diagnostic Criteria",division:"Neuromuskuler",tags:["diagnosis"],hasCalc:false},
  {name:"INCAT",full:"Inflammatory Neuropathy Cause and Treatment Disability Scale",division:"Neuromuskuler",tags:["severity","monitoring"],hasCalc:false},
  // NEUROKRITIS
  {name:"RASS",full:"Richmond Agitation-Sedation Scale",division:"Neuro-ICU",tags:["monitoring","treatment"],hasCalc:true},
  {name:"CAM-ICU",full:"Confusion Assessment Method for ICU",division:"Neuro-ICU",tags:["screening","diagnosis"],hasCalc:false},
  {name:"GOS-E",full:"Glasgow Outcome Scale-Extended — TBI",division:"Neuro-ICU",tags:["prognosis"],hasCalc:true},
  {name:"Marshall CT",full:"Marshall CT Classification — TBI",division:"Neuro-ICU",tags:["severity","treatment"],hasCalc:false},
  {name:"IMPACT Score",full:"International Mission for Prognosis in TBI",division:"Neuro-ICU",tags:["prognosis"],hasCalc:false},
  {name:"BPS",full:"Behavioral Pain Scale — Pasien Terintubasi",division:"Neuro-ICU",tags:["monitoring","severity"],hasCalc:true},
  {name:"Koreksi Elektrolit",full:"Kalkulator Koreksi Elektrolit — Na / K / Ca / Mg / PO4",division:"Neuro-ICU",tags:["treatment","monitoring"],hasCalc:true},
  {name:"Osmolaritas",full:"Kalkulator Osmolaritas Serum & Osmol Gap",division:"Neuro-ICU",tags:["diagnosis","monitoring"],hasCalc:true},
  // NEUROREHABILITASI
  {name:"Fugl-Meyer UE",full:"Fugl-Meyer Assessment — Upper Extremity",division:"Neurorehabilitasi",tags:["monitoring","severity"],hasCalc:false},
  {name:"Modified Ashworth",full:"Modified Ashworth Scale for Spasticity",division:"Neurorehabilitasi",tags:["severity","treatment"],hasCalc:true},
  {name:"TUG Test",full:"Timed Up and Go Test",division:"Neurorehabilitasi",tags:["monitoring","screening"],hasCalc:false},
  {name:"Berg Balance",full:"Berg Balance Scale",division:"Neurorehabilitasi",tags:["monitoring","severity"],hasCalc:false},
  {name:"BMI",full:"BMI / Indeks Massa Tubuh — WHO & Asia-Pacific",division:"Neurorehabilitasi",tags:["screening","diagnosis"],hasCalc:true},
  // TIDUR
  {name:"ESS",full:"Epworth Sleepiness Scale",division:"Sleep Neurology",tags:["screening","severity"],hasCalc:true},
  {name:"PSQI",full:"Pittsburgh Sleep Quality Index",division:"Sleep Neurology",tags:["screening","monitoring"],hasCalc:false},
  {name:"IRLS",full:"International Restless Legs Syndrome Rating Scale",division:"Sleep Neurology",tags:["severity","monitoring"],hasCalc:false},
  // NEUROKHUSUS
  {name:"SARA",full:"Scale for Assessment and Rating of Ataxia",division:"Neurokhusus",tags:["severity","monitoring"],hasCalc:false},
  {name:"UHDRS Motor",full:"Unified Huntington's Disease Rating Scale — Motor",division:"Neurokhusus",tags:["severity","monitoring"],hasCalc:false},
  {name:"COMPASS-31",full:"Composite Autonomic Symptom Score-31",division:"Neurokhusus",tags:["diagnosis","monitoring"],hasCalc:false},
  {name:"UMSARS",full:"Unified Multiple System Atrophy Rating Scale",division:"Neurokhusus",tags:["severity","monitoring"],hasCalc:false},
  {name:"Fazekas Scale",full:"Fazekas Scale — White Matter Hyperintensities (WMH) MRI",division:"Neurokhusus",tags:["severity","diagnosis"],hasCalc:true},
  {name:"Nuartha Score",full:"Skor Nuartha — Diferensiasi Stroke Iskemik vs Hemoragik",division:"Neurokhusus",tags:["diagnosis","screening"],hasCalc:true},
  // NEURO-ONKOLOGI
  {name:"Tokuhashi Score",full:"Revised Tokuhashi Scoring System — Spinal Metastasis",division:"Neuro-Onkologi",tags:["prognosis","treatment"],hasCalc:true},
  {name:"SINS",full:"Spinal Instability Neoplastic Score",division:"Neuro-Onkologi",tags:["diagnosis","severity"],hasCalc:true},
  {name:"KPS",full:"Karnofsky Performance Status Scale",division:"Neuro-Onkologi",tags:["severity","monitoring"],hasCalc:true},
  {name:"ECOG",full:"Eastern Cooperative Oncology Group Performance Status",division:"Neuro-Onkologi",tags:["severity","monitoring"],hasCalc:true},
  {name:"TMZ Stupp",full:"Dosis Temozolomide (TMZ) — Stupp Protocol untuk GBM",division:"Neuro-Onkologi",tags:["treatment"],hasCalc:true},
  // PREOPERATIF
  {name:"STRAS Score",full:"Perioperative Stroke Risk Assessment Score",division:"Preoperatif",tags:["prognosis","screening"],hasCalc:true},
  {name:"Magedanz Score",full:"Magedanz Risk Score — Stroke After Cardiac Surgery",division:"Preoperatif",tags:["prognosis","screening"],hasCalc:true},
  {name:"ACS Risk Calculator",full:"American College of Surgeons NSQIP Surgical Risk Calculator",division:"Preoperatif",tags:["prognosis","screening"],hasCalc:false},
];
